# Generated by Django 4.0.3 on 2022-03-10 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('buy_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='families.family')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='remedies.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['-created_on'], name='remedies_pu_created_346fd0_idx'),
        ),
    ]
