# Generated by Django 4.0.3 on 2022-03-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0002_purchase_purchase_remedies_pu_created_346fd0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='units',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
