# Generated by Django 4.0.3 on 2022-04-09 21:15
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0003_purchase_units'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
