# Generated by Django 4.0.3 on 2022-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0004_auto_20220409_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
