# Generated by Django 4.0.3 on 2022-04-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remedies', '0005_purchase_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to=settings.AUTH_USER_MODEL),
        ),
    ]
