# Generated by Django 4.0.3 on 2022-03-10 20:42

import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Revoked')], default='PE', max_length=2)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='families.family')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['-created_on'], name='families_fa_created_5346f9_idx'),
        ),
    ]
