# Generated by Django 4.0.3 on 2022-03-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0002_familyinvitation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyinvitation',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='created_invitations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
