# Generated by Django 4.0.3 on 2022-04-12 23:39

import uuid

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRestoreRequest',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='passwordrestorerequest',
            index=models.Index(fields=['-created_on'], name='users_passw_created_9b92a8_idx'),
        ),
    ]
