# Generated by Django 4.0.3 on 2022-04-15 16:26

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordrestorerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrestorerequest',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=255),
        ),
    ]
