name: PR

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  workflow_call:
    outputs:
      success:
        description: "Lint & Test"
        value: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check formatting (black)
        run: python -m black --check .
      - name: Check import ordering (isort)
        run: python -m isort --check .
      - name: Check linting (flake8)
        run: python -m flake8

  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: medicines
        # Wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          RUN_ENV: DEV
        run: |
          python -m pytest --cache-clear --showlocals --verbose .
